import {
  AGGR_FUNCTIONS_ENUM,
  MATH_FUNCTIONS_ENUM,
  RANGE_FUNCTIONS_ENUM,
  DATE_FUNCTIONS_ENUM,
  COMPLEX_FUNCTIONS_ENUM,
  OTHER_FUNCTIONS_ENUM,
  STRING_FUNCTIONS_ENUM,
} from './definitions';

export const AGGR_FUNCTIONS_LIST = Object.values(AGGR_FUNCTIONS_ENUM);
export const MATH_FUNCTIONS_LIST = Object.values(MATH_FUNCTIONS_ENUM);
export const RANGE_FUNCTIONS_LIST = Object.values(RANGE_FUNCTIONS_ENUM);
export const DATE_FUNCTIONS_LIST = Object.values(DATE_FUNCTIONS_ENUM);
export const COMPLEX_FUNCTIONS_LIST = Object.values(COMPLEX_FUNCTIONS_ENUM);
export const OTHER_FUNCTIONS_LIST = Object.values(OTHER_FUNCTIONS_ENUM);
export const STRING_FUNCTIONS_LIST = Object.values(STRING_FUNCTIONS_ENUM);

export const ALL_ODPS_FUNCTION_LIST = [
  ...AGGR_FUNCTIONS_LIST,
  ...MATH_FUNCTIONS_LIST,
  ...RANGE_FUNCTIONS_LIST,
  ...DATE_FUNCTIONS_LIST,
  ...COMPLEX_FUNCTIONS_LIST,
  ...OTHER_FUNCTIONS_LIST,
  ...STRING_FUNCTIONS_LIST,
];
