declare module '@alipay/alex/languages' {}
declare module '@alipay/alex/languages/bat' {}
declare module '@alipay/alex/languages/clojure' {}
declare module '@alipay/alex/languages/coffeescript' {}
declare module '@alipay/alex/languages/cpp' {}
declare module '@alipay/alex/languages/csharp' {}
declare module '@alipay/alex/languages/css' {}
declare module '@alipay/alex/languages/docker' {}
declare module '@alipay/alex/languages/fsharp' {}
declare module '@alipay/alex/languages/go' {}
declare module '@alipay/alex/languages/groovy' {}
declare module '@alipay/alex/languages/handlebars' {}
declare module '@alipay/alex/languages/hlsl' {}
declare module '@alipay/alex/languages/html' {}
declare module '@alipay/alex/languages/ini' {}
declare module '@alipay/alex/languages/java' {}
declare module '@alipay/alex/languages/javascript' {}
declare module '@alipay/alex/languages/json' {}
declare module '@alipay/alex/languages/less' {}
declare module '@alipay/alex/languages/log' {}
declare module '@alipay/alex/languages/lua' {}
declare module '@alipay/alex/languages/make' {}
declare module '@alipay/alex/languages/markdown' {}
declare module '@alipay/alex/languages/objective-c' {}
declare module '@alipay/alex/languages/perl' {}
declare module '@alipay/alex/languages/php' {}
declare module '@alipay/alex/languages/powershell' {}
declare module '@alipay/alex/languages/pug' {}
declare module '@alipay/alex/languages/python' {}
declare module '@alipay/alex/languages/razor' {}
declare module '@alipay/alex/languages/ruby' {}
declare module '@alipay/alex/languages/rust' {}
declare module '@alipay/alex/languages/scss' {}
declare module '@alipay/alex/languages/shaderlab' {}
declare module '@alipay/alex/languages/shellscript' {}
declare module '@alipay/alex/languages/sql' {}
declare module '@alipay/alex/languages/swift' {}
declare module '@alipay/alex/languages/typescript' {}
declare module '@alipay/alex/languages/vb' {}
declare module '@alipay/alex/languages/xml' {}
declare module '@alipay/alex/languages/yaml' {}
