declare module '@codeblitzjs/ide-core/languages' {}
declare module '@codeblitzjs/ide-core/languages/arm' {}
declare module '@codeblitzjs/ide-core/languages/bat' {}
declare module '@codeblitzjs/ide-core/languages/clojure' {}
declare module '@codeblitzjs/ide-core/languages/coffeescript' {}
declare module '@codeblitzjs/ide-core/languages/cpp' {}
declare module '@codeblitzjs/ide-core/languages/csharp' {}
declare module '@codeblitzjs/ide-core/languages/css' {}
declare module '@codeblitzjs/ide-core/languages/docker' {}
declare module '@codeblitzjs/ide-core/languages/fsharp' {}
declare module '@codeblitzjs/ide-core/languages/go' {}
declare module '@codeblitzjs/ide-core/languages/groovy' {}
declare module '@codeblitzjs/ide-core/languages/handlebars' {}
declare module '@codeblitzjs/ide-core/languages/hlsl' {}
declare module '@codeblitzjs/ide-core/languages/html' {}
declare module '@codeblitzjs/ide-core/languages/ini' {}
declare module '@codeblitzjs/ide-core/languages/java' {}
declare module '@codeblitzjs/ide-core/languages/javascript' {}
declare module '@codeblitzjs/ide-core/languages/json' {}
declare module '@codeblitzjs/ide-core/languages/kcl-vscode-extension' {}
declare module '@codeblitzjs/ide-core/languages/kotlin' {}
declare module '@codeblitzjs/ide-core/languages/less' {}
declare module '@codeblitzjs/ide-core/languages/linkerscript' {}
declare module '@codeblitzjs/ide-core/languages/log' {}
declare module '@codeblitzjs/ide-core/languages/lua' {}
declare module '@codeblitzjs/ide-core/languages/make' {}
declare module '@codeblitzjs/ide-core/languages/markdown' {}
declare module '@codeblitzjs/ide-core/languages/objective-c' {}
declare module '@codeblitzjs/ide-core/languages/perl' {}
declare module '@codeblitzjs/ide-core/languages/php' {}
declare module '@codeblitzjs/ide-core/languages/powershell' {}
declare module '@codeblitzjs/ide-core/languages/pug' {}
declare module '@codeblitzjs/ide-core/languages/python' {}
declare module '@codeblitzjs/ide-core/languages/r' {}
declare module '@codeblitzjs/ide-core/languages/razor' {}
declare module '@codeblitzjs/ide-core/languages/ruby' {}
declare module '@codeblitzjs/ide-core/languages/rust' {}
declare module '@codeblitzjs/ide-core/languages/scheme' {}
declare module '@codeblitzjs/ide-core/languages/scss' {}
declare module '@codeblitzjs/ide-core/languages/shaderlab' {}
declare module '@codeblitzjs/ide-core/languages/shellscript' {}
declare module '@codeblitzjs/ide-core/languages/solidity-lang' {}
declare module '@codeblitzjs/ide-core/languages/sql' {}
declare module '@codeblitzjs/ide-core/languages/swift' {}
declare module '@codeblitzjs/ide-core/languages/typescript' {}
declare module '@codeblitzjs/ide-core/languages/vb' {}
declare module '@codeblitzjs/ide-core/languages/velocity' {}
declare module '@codeblitzjs/ide-core/languages/vscode-proto3' {}
declare module '@codeblitzjs/ide-core/languages/vue' {}
declare module '@codeblitzjs/ide-core/languages/xml' {}
declare module '@codeblitzjs/ide-core/languages/yaml' {}
